version: '3.8'

services:
  app:
    build: .
    container_name: node_mysql
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=Thongminh@2906
      - DB_NAME=testdb
    depends_on:
      - mysql
    volumes:
      - .:/appMysql
      - /appMysql/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Thongminh@2906
      - MYSQL_DATABASE=testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
